version: '3.3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"  # Change to an unused port on the host
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
